import { ReduxProvider } from "@/components/ReduxProvider";
import "./globals.scss";
import { QueryProvider } from "@/components/QueryProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ReduxProvider>
        <body>
          <QueryProvider>{children}</QueryProvider>
        </body>
      </ReduxProvider>
    </html>
  );
}
